import { TimerProvider } from './TimerContext'
import './globals.css'
import { Poppins } from 'next/font/google'


const inter = Poppins({ subsets: ['latin'], weight:"400" })

export const metadata = {
  title: 'Purrfect Plate',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <TimerProvider>
      <body className={inter.className}>
        {children}
        </body>
      </TimerProvider>
 
    </html>
  )
}
